travis:
  secure:
    BINSTAR_TOKEN: TB73VcgFvjSPAlorbD/Y0ZkJ5ZqwOOFY3s5Ricu1fyVsFdeOHWdqLpgAIDaoCTi7+65DM/ZSP20Tm92Get/4HypTBHGxNgFoW2n3SenH4HYuTyRlrFp1k9b1pFLR+Mn/cNr+TfSM1srfp+phcb7FTU+yEPrrMWq81Fyr1arNSGZorjYdoEvcsafGLRAKlMfN0dCc8ll2XD2VkZLYHQ8SlIZmtbRHD/jqYZxAyMEo5MZ9yAJkuevR0CR7OcQtBOHvLud20cAEi3sMYmNZ446H/qSHuAfsJrtHbBgrcYQsWovkG2Zk2mmg9J8tTrwqau3gl+ohPimp83o1xp5+Ats0hQufBA6gOnX1H6ZeuPeyPIcg/th/VwdNg5PedjpX1XZjk3hM+mBYlv7h4YPjN1uKdOZ0rOx5HoH3e95hws/JuztqGvfljzl/WUG9wI2a1JLV4I2MJMTuxZLd0Fp336t1/vfOPUDxptjXbI1Js7U9Fi8wpEn+vWBvdfe2cwgIADRPgaFDYLHYq5A6SWINcSV+Ih+y8UTBIuAFOYdKtZGnlLq14dy20MopzYm+UvRfIkPkvspTXYV81GxWGz5+UlNsEbUmgQetMcPvPO2IYTC86m7Zdy7mIbPxtC9cUrXlHeo//uqBvZb31NcvqHrDtV1PaOY71/P+ZkIP7ag4naHsLPg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
