travis:
  secure:
    BINSTAR_TOKEN: oinZGMe89Hr0sS5pXvdvDk0VaATkW0wbWGDjhJRMgLnqdvdDuvNcVdOI156YIvus9QHTAovN+npMxQ5PGXv2vdMTF6z0O2LGI1bKP1LW2IxCRibqepYi7BFVVFfwE2FYVyDzm9u3b0rWJxdvqTT4xonibsN1BQOwKZA67/7oG3+Np0PaRJ4ubakfJJN1bCgmFohSO2ubaivJEodFGuV4ge0HzNcnj1cpDWHygUUxJEwMKevpteSUkx9U5exw7aMiZGTADFmazEyf/CsMVsWV6UNdV6P1IVXQP0/RY9stXNuOg/l87p/0W85Wd4Y0AspNMMYgZjmHlAo3UdysdxTrgkj8CiGCQJUxM74fI0hSmsh+Ao/7N8Pkcypq8sIT/aD9zYjFSYwLfKWuxEOMSgUdt6mFN6v+BbEYsg8dVL+wFbUKDENstlrfx7EvhrOz1QgUmhGBDxq/Z7Sv5fKszzjRDiEhV5RL/iOsGzalpaYGMeWxCdIkpD8qes6/aYGqQHcpFhdC1s22hr+MJxPHnPeISFwScetZbc5rrHjJKqPUzEZ+UoQsGkfwvpSsMIMNLKEK6koyizqlJpHDsq9fS6QXBaoofSZaTrTYi4zDvties0bDxBRw1ofVZpZKa+89/KlluwSJINvQqjWuH9F9rgTZIGJcgfdmb/6tYyBB07BRi4E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
