travis:
  secure:
    BINSTAR_TOKEN: Izv5u57jgQaSL1YygwGyu8gJMr9z3FjQd4EDwx2KxIVBRTwzI+v1DJs+wFFpdxcfDG8N82/Q46UiZxJIpyc491GYHHsUvq5geokp1vFnStb6gbAB4jBvuPF3jI/SXGwP42ti+Oebn+yU3ZFgS5sjCrEa/MhmYxtdg0YySkNoboGPMzF9tCHqO91NceJQ5/hO+C/vt77ppTgv4WetsrEm9EV5DmV4KPp1LvyW+9zMf4ZfMaMI4A5UslRFTfhw0et6fjqu/Jb5HXhk+TXy1AJRYvrFqo1dMwB2ylo4iasJah0U5bz2bMXb8JLZMNM1iwa3W0TUE9iGTWq16iV9h1NOcwlpkYKYNJDFZXq6PVhnnxB8RLxEcHguwbLDYxEReZhJEiuWzBuB/zndZk6SLuA6sENPmgNUUZQnJ7W+O+ZFSyBKFkBr6uuk7DQ2u/8XTZUT1ikx3k+o9VpSMfU3bolgojvgw68FtNZJmYQyQaEa2h1jU+PgtrYatR4OcuSBZtfNBOGMOWnf1Pn57owubq11Vcohl5wCV/I9qfBpm3rkPjjISEonwJAGdijnV2wfwN0AYjUNVwABA3TndPlx+ZePHxp7p0bhCp40pwTToTYAqx8LtYzZWwrnPLNmL981GVKONqVduXX+2kst9fzQQvMqECLy8T5G9166KFdVzs4W1cg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
