travis:
  secure:
    BINSTAR_TOKEN: bcGbimTj2Bi/2xzHhpAu18glAnoomJZB9gQaqYeNNSAIvKqcL8oHsK4j7sg2woPBcilcHwpiES6ZabDKJnUHoiI6uzKsx2SlFqcjLAdUKGDJWtBsAuRv/w+lG9auUOHuz2rFnCacbMM/1LaPRdE5s8ovWPMJ5pOgfvJQzoYWBa3D+ADBjdCUbvMXCp/0veq1UaoT8C1cd3DEg20kYmV+w/z2yxXZTc3AsvAedcRf73ILG1pWrGv87oF/y9hGLavbHdqFh+voeDOwpIv9D16o22aXConmnt+ICEEu0ize4s5WdjdW4XQnLjYwXFJNqNq7e54+/2uZKbOVzt+nplnmhzn/V441pk+0zNraktxDLc/y5exETZnsqGeAm/1nCVHgBoGd5JdW4AtF2O0PsiBYThYHT0D7zJU/S9bYbSLe6OkHeh6xawEQPHD6s53PAkWyPG42XCeSvdrQ6XjUBZVu8HFDfPQ+ZILYR+lYmSRI9l/jVSBPm/sWJwk+h12GO3hQEG6phACpwgB62tT/z5Tq3C8S8yIgRhbRzsCVNDXYxZWRDB8VBmTlKxY+pHLfxOG2ayOoYp0MHt7rkRepGHPTxeq2kCb1Cym7b/HDMDj9DaEbzvGQA52D1VCcmA91wSxmA/GKUj/HMV29MjcWW69g/CTVtQc5zNcXEZwnxc+GU2I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
